# Workflow for evaluting how many modules are covered by WAF tests compared to the baseline
name: .Platform - Get WAF test coverage

on:
  schedule:
    - cron: "30 4 * * *" # Every day at 4:30 am
  workflow_dispatch:

jobs:
  get-WAF-test-coverage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TEAM_LINTER_APP_ID }}
          private_key: ${{ secrets.TEAM_LINTER_PRIVATE_KEY }}
      - name: Grab artifacts from runs
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'platform' 'Get-WafTestCoverage.ps1')

          $functionInput = @{
            Repo     = "${{ github.repository_owner }}/${{ github.event.repository.name }}"
            RepoRoot = $env:GITHUB_WORKSPACE
            LimitNumberOfRuns = 500
            LimitInDays       = 2
          }

          Get-WafTestCoverage @functionInput -Verbose
